# -*- coding: utf-8 -*-
"""Data_fetcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdV1nRQ9uAJZziA5ec75nmsarAY5irEz
"""

import os
import time
import requests
import pandas as pd
from tqdm import tqdm

# 0. MOUNT GOOGLE DRIVE (COLAB)
# =====================================================
from google.colab import drive
drive.mount("/content/drive")
BASE_PATH = "/content/drive/MyDrive/Satellite Imagery Based Property Valuation"

# 1. CONFIGURATION

MAPBOX_TOKEN = "pk.eyJ1IjoicmlzaGFiaDE1IiwiYSI6ImNtamN0NGt6cDBuNXUzZXNjbXJxMGgxY3kifQ.g0OdeWCW2x694NaYNv5FzQ"

STYLE = "mapbox/satellite-v9"
ZOOM = 17
IMG_SIZE = "512x512"
PITCH = 0
BEARING = 0

BASE_URL = "https://api.mapbox.com/styles/v1"

BASE_DIR = "/content/drive/MyDrive/Satellite Imagery Based Property Valuation"

TRAIN_CSV = f"{BASE_DIR}/train(1).csv"
TEST_CSV  = f"{BASE_DIR}/test2.csv"

TRAIN_IMG_DIR = f"{BASE_DIR}/images/train"
TEST_IMG_DIR  = f"{BASE_DIR}/images/test"

RATE_LIMIT_SLEEP = 0.1

# 2. CREATE DIRECTORIES

os.makedirs(TRAIN_IMG_DIR, exist_ok=True)
os.makedirs(TEST_IMG_DIR, exist_ok=True)

# 3. IMAGE DOWNLOAD FUNCTION

def download_image(lat, lon, save_path):
    url = (
        f"{BASE_URL}/{STYLE}/static/"
        f"{lon},{lat},{ZOOM},{BEARING},{PITCH}/"
        f"{IMG_SIZE}"
        f"?access_token={MAPBOX_TOKEN}"
    )

    response = requests.get(url, timeout=10)

    if response.status_code == 200:
        with open(save_path, "wb") as f:
            f.write(response.content)
        return True
    else:
        return False

# 4. PROCESS A DATASET

def process_dataset(csv_path, image_dir):
    df = pd.read_csv(csv_path)

    required_cols = {"id", "lat", "long"}
    assert required_cols.issubset(df.columns), \
        f"CSV must contain {required_cols}"

    success, failed = 0, 0

    for _, row in tqdm(df.iterrows(), total=len(df)):
        prop_id = row["id"]
        lat = row["lat"]
        lon = row["long"]

        img_path = os.path.join(image_dir, f"{prop_id}.png")

        if os.path.exists(img_path):
            continue

        ok = download_image(lat, lon, img_path)

        if ok:
            success += 1
        else:
            failed += 1

        time.sleep(RATE_LIMIT_SLEEP)

    print(f"Downloaded: {success}")
    print(f"Failed     : {failed}")

# 5. MAIN

if __name__ == "__main__":
    print("Downloading TRAIN images...")
    process_dataset(TRAIN_CSV, TRAIN_IMG_DIR)

    print("\nDownloading TEST images...")
    process_dataset(TEST_CSV, TEST_IMG_DIR)

    print("\nImages saved permanently to Google Drive ✔")

TRAIN_IMG_DIR = f"{BASE_PATH}/images/train"
TEST_IMG_DIR  = f"{BASE_PATH}/images/test"